### ISSUE TITLE
损失

### ISSUE THREAD

**Issue by NanWangAC** [RSIDEA-WHU2020/Auto-AD#1]
您好，我用了您的开源代码，发现只有在HYDICE上表现较好，AUC约为96%。但在其他数据集如abu或者Sandiego表现都非常差，重构的损失很大基本不下降，请问最可能是的原因是什么？如果是调参问题，情况有什么经验可以借鉴？方便的时候麻烦您回一下消息。

**Comment by RSIDEA-WHU2020** [comment]
感谢关注，Auto-AD方法基于小目标假设，本身可能并不特别适用于Sandiego这种目标较大的数据集。对于精度不好的问题，可以适当降低阈值进行调参。

**Comment by NanWangAC** [comment]
非常感谢您的回复，已经解答了我的疑问，如果方便的话，能不能给我发一个文章中所用数据集的下载链接，我想在您这项工作的基础上继续往下做一下，目前只找到了文章中的部分数据集，麻烦您了。

**Comment by RSIDEA-WHU2020** [comment]
新的数据还在整理过程中，有新数据会更新在RSIDEA小组资源共享网站，敬请关注。
RSIDEA小组资源共享页面：http://rsidea.whu.edu.cn/resource_sharing.htm

**Comment by wangk98** [comment]
> 您好，我用了您的开源代码，发现只有在HYDICE上表现较好，AUC约为96%。但在其他数据集如abu或者Sandiego表现都非常差，重构的损失很大基本不下降，请问最可能是的原因是什么？如果是调参问题，情况有什么经验可以借鉴？方便的时候麻烦您回一下消息。

您好，请问你有修改相关参数嘛，为什么我利用作者提供的代码在HYDICE上的AUC结果只有54%。
